name: kf_drawer
description: Side menu (Drawer)
version: 1.1.1
author: qqmikey <qqmikey@icloud.com>
homepage: https://github.com/qqmikey/kf_drawer

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
